### ISSUE TITLE
Edit / view from one interface

### ISSUE THREAD

**Issue by codemedic** [Magnushhoie/fuz#2]
Thanks for creating this awesome tool! I have been using this afternoon to navigate my got repos and notes; it just works!

Would it be possible to edit or view the selected file, without having to choose the option from commandline?
i.e. search and highlight the file, then pressing `Enter` would view the file while `Shift+Enter` would edit the file.

Cheers!

**Comment by Magnushhoie** [comment]
Hi codemedic, what a fantastic idea!

I have implemented Ctrl + O (open vim) and Ctrl + L (view with less) in the dev branch: https://github.com/Magnushhoie/fuz/tree/dev

I'll push to main after testing for a few days.
